Repository CCorrado/ssw690ossmgmt, pull requests merged in 2019-02, with the labels that each got.

#8 Issue 3 Set up Android project
  .gitignore
  .travis.yml
  README.md
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/coverage.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/ccorrads/ossp/HomeActivity.kt
  android/app/src/main/java/com/ccorrads/ossp/OSSPApp.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/layout/activity_home.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/test/java/com/ccorrads/ossp/HomeTests.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  architecture.png
  ossp_arch.xml
Labels: Frontend

#30 Architecture Diagram
  architecture.png
  ossp_arch.png
  ossp_arch.xml
Labels: Documentation

#31 Adding the proposal to the repo
  OSSP Proposal.docx
Labels: Documentation

#37 Adding dependencies and core structure.
  android/CHANGELOG.md
  android/README.md
  android/app/build.gradle
  android/app/src/main/java/com/ccorrads/ossp/HomeActivity.kt
  android/build.gradle
  android/core/.gitignore
  android/core/build.gradle
  android/core/proguard-rules.pro
  android/core/src/androidTest/java/com/ccorrads/ossp/core/ExampleInstrumentedTest.java
  android/core/src/main/AndroidManifest.xml
  android/core/src/main/java/com/ccorrads/ossp/core/BaseActivity.kt
  android/core/src/main/java/com/ccorrads/ossp/core/BaseFragment.kt
  android/core/src/main/java/com/ccorrads/ossp/core/ErrorView.kt
  android/core/src/main/java/com/ccorrads/ossp/core/Mvp.kt
  android/core/src/main/java/com/ccorrads/ossp/core/views/BaseFullscreenDialogFragment.kt
  android/core/src/main/java/com/ccorrads/ossp/core/views/WaitDialogFragment.kt
  android/core/src/main/res/layout/fragment_dialog_wait.xml
  android/core/src/main/res/values-v23/styles.xml
  android/core/src/main/res/values-v27/styles.xml
  android/core/src/main/res/values/colors.xml
  android/core/src/main/res/values/dimens.xml
  android/core/src/main/res/values/strings.xml
  android/core/src/main/res/values/styles.xml
  android/core/src/test/java/com/ccorrads/ossp/core/ExampleUnitTest.java
  android/settings.gradle
Labels: Frontend

#41 Feature/gateway/express gateway (gateway first demo with express-gateway framework)
  .gitignore
  .travis.yml
  gateway-test/.vs/ProjectSettings.json
  gateway-test/.vs/VSWorkspaceState.json
  gateway-test/.vs/config/applicationhost.config
  gateway-test/.vs/gateway-test/v15/.suo
  gateway-test/.vs/slnx.sqlite
  gateway-test/.yo-rc.json
  gateway-test/config/gateway.config.yml
  gateway-test/config/models/applications.json
  gateway-test/config/models/credentials.json
  gateway-test/config/models/users.json
  gateway-test/config/system.config.yml
  gateway-test/package-lock.json
  gateway-test/package.json
  gateway-test/server.js
Labels: API
