Repository CCorrado/ssw690ossmgmt, pull requests merged in 2019-04, with the labels that each got.

#56 Implemented orders and business and users
  .gitignore
  .travis.yml
  database/.gitignore
  database/Dockerfile
  database/README.md
  database/bao-web-app/mvnw
  database/bao-web-app/mvnw.cmd
  database/bao-web-app/ossmgmt/business.ibd
  database/bao-web-app/ossmgmt/inventory.ibd
  database/bao-web-app/ossmgmt/order.ibd
  database/bao-web-app/ossmgmt/sale.ibd
  database/bao-web-app/ossmgmt/user.ibd
  database/bao-web-app/pom.xml
  database/bao-web-app/src/main/java/bao/webapp/BaoWebApp.java
  database/bao-web-app/src/main/java/bao/webapp/UserController.java
  database/bao-web-app/src/main/java/bao/webapp/model/User.java
  database/bao-web-app/src/main/java/bao/webapp/repository/UserRepository.java
  database/bao-web-app/src/main/java/bao/webapp/service/UserService.java
  database/bao-web-app/src/main/java/bao/webapp/service/UserServiceImpl.java
  database/bao-web-app/src/main/resources/application.properties
  database/bao-web-app/src/test/java/bao/webapp/BaoWebAppTests.java
  database/bao-web-app/test_db_01/roles.ibd
  database/bao-web-app/test_db_01/users.ibd
  database/build.gradle
  database/docker-compose.yml
  database/gradle/wrapper/gradle-wrapper.jar
  database/gradle/wrapper/gradle-wrapper.properties
  database/gradlew
  database/gradlew.bat
  database/settings.gradle
  database/src/main/kotlin/com/ossp/database/DatabaseApplication.kt
  database/src/main/kotlin/com/ossp/database/controller/UserController.kt
  database/src/main/kotlin/com/ossp/database/model/AuthInfo.kt
  database/src/main/kotlin/com/ossp/database/model/Business.kt
  database/src/main/kotlin/com/ossp/database/model/Order.kt
  database/src/main/kotlin/com/ossp/database/model/User.kt
  database/src/main/kotlin/com/ossp/database/repository/BusinessRepository.kt
  database/src/main/kotlin/com/ossp/database/repository/OrderRepository.kt
  database/src/main/kotlin/com/ossp/database/repository/UserRepository.kt
  database/src/main/kotlin/com/ossp/database/service/UserService.kt
  database/src/main/kotlin/com/ossp/database/service/UserServiceImpl.kt
  database/src/main/resources/application.properties
  database/src/test/kotlin/com/ossp/database/DatabaseApplicationTests.kt
Labels: Business Owner, Buyer, Database

#58 Feature/gateway/deploy docker
  .travis.yml
  gateway-test/.gitignore
  gateway-test/.vs/ProjectSettings.json
  gateway-test/.vs/slnx.sqlite
  gateway-test/app.js
  gateway-test/routes/database/db_register.js
  gateway-test/routes/frontend/frontend_login.js
  gateway-test/routes/frontend/frontend_register.js
  gateway-test/routes/index.js
  gateway-test/routes/login.js
  gateway-test/routes/microservices/micro_login.js
  microservices/app/__init__.py
  microservices/config.py
Labels: API

#59 Docker configuration for entire platform.
  .travis.yml
  android/core/build.gradle
  android/core/src/main/java/com/ccorrads/ossp/core/network/BackendService.kt
  android/core/src/main/java/com/ccorrads/ossp/core/network/models/RegisterRequest.kt
  android/loginregistration/build.gradle
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/registration/injection/RegisterPresenter.kt
  database/.dockerignore
  database/Dockerfile
  database/db.env
  database/docker-compose.yml
  docker-compose.yml
  gateway-test/Dockerfile
  gateway-test/docker-compose.yml
  microservices/.dockerignore
  microservices/Dockerfile
  microservices/app/__init__.py
  microservices/config.py
  microservices/dev.env
  microservices/docker-compose.yml
Labels: enhancement

#61 Refactored the API. Access the swagger 127.0.0.1:3000/api-docs
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/core/build.gradle
  android/core/src/main/java/com/ccorrads/ossp/core/database/OSSPDb.kt
  android/core/src/main/java/com/ccorrads/ossp/core/database/models/Auth.kt
  android/core/src/main/java/com/ccorrads/ossp/core/injection/NetworkModule.kt
  android/core/src/main/java/com/ccorrads/ossp/core/network/BackendService.kt
  android/core/src/main/java/com/ccorrads/ossp/core/network/models/UserResponse.kt
  android/gradle/wrapper/gradle-wrapper.properties
  android/loginregistration/build.gradle
  android/loginregistration/src/main/AndroidManifest.xml
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/injection/LoginRegisterPresenter.kt
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/registration/injection/RegisterPresenter.kt
  android/loginregistration/src/test/java/com/ccorrads/ossp/loginregistration/LoginTests.kt
  android/loginregistration/src/test/java/com/ccorrads/ossp/loginregistration/RegistrationTests.kt
  database/src/main/kotlin/com/ossp/database/controller/UserController.kt
  database/src/main/kotlin/com/ossp/database/error/ObjectNotCreated.kt
  database/src/main/kotlin/com/ossp/database/error/ObjectNotFound.kt
  database/src/main/kotlin/com/ossp/database/model/Session.kt
  database/src/main/kotlin/com/ossp/database/model/User.kt
  database/src/main/kotlin/com/ossp/database/model/UserSessionResponse.kt
  database/src/main/kotlin/com/ossp/database/repository/SessionRepository.kt
  database/src/main/kotlin/com/ossp/database/repository/UserRepository.kt
  database/src/main/kotlin/com/ossp/database/service/UserServiceImpl.kt
  database/src/main/kotlin/com/ossp/database/service/session/SessionService.kt
  database/src/main/kotlin/com/ossp/database/service/session/SessionServiceImpl.kt
  database/src/main/kotlin/com/ossp/database/service/user/UserService.kt
  database/src/main/kotlin/com/ossp/database/service/user/UserServiceImpl.kt
  database/src/main/resources/application.properties
  gateway-test/.vs/slnx.sqlite
  gateway-test/Dockerfile
  gateway-test/README.md
  gateway-test/app.js
  gateway-test/bin/www.js
  gateway-test/cert.pem
  gateway-test/errors/HttpError.js
  gateway-test/errors/OAuthError.js
  gateway-test/errors/UserError.js
  gateway-test/key.pem
  gateway-test/middleware/checkAccessToken.js
  gateway-test/middleware/errorHandler.js
  gateway-test/models/clients.json
  gateway-test/models/users.json
  gateway-test/package-lock.json
  gateway-test/package.json
  gateway-test/routes/currentSession/currentSession.js
  gateway-test/routes/currentSession/index.js
  gateway-test/routes/database/db_register.js
  gateway-test/routes/frontend/frontend_login.js
  gateway-test/routes/frontend/frontend_register.js
  gateway-test/routes/index.js
  gateway-test/routes/login.js
  gateway-test/routes/microservices/micro_login.js
  gateway-test/routes/users/createUser.js
  gateway-test/routes/users/getUser.js
  gateway-test/routes/users/loginUser.js
  gateway-test/views/error.jade
  gateway-test/views/index.jade
  gateway-test/views/layout.jade
Labels: API, Documentation

#62 Add Home module.
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/ccorrads/ossp/MainActivity.kt
  android/app/src/main/java/com/ccorrads/ossp/OSSPApp.kt
  android/app/src/main/java/com/ccorrads/ossp/OSSPComponent.kt
  android/app/src/main/res/drawable/ic_home.xml
  android/app/src/main/res/drawable/ic_settings.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/test/java/com/ccorrads/ossp/MainTests.kt
  android/build.gradle
  android/core/build.gradle
  android/core/src/main/java/com/ccorrads/ossp/core/BaseApplication.kt
  android/core/src/main/java/com/ccorrads/ossp/core/Router.kt
  android/core/src/main/java/com/ccorrads/ossp/core/database/OSSPDb.kt
  android/core/src/main/java/com/ccorrads/ossp/core/database/models/Auth.kt
  android/core/src/main/java/com/ccorrads/ossp/core/database/models/User.kt
  android/core/src/main/java/com/ccorrads/ossp/core/injection/DatabaseModule.kt
  android/core/src/main/java/com/ccorrads/ossp/core/injection/NetworkModule.kt
  android/core/src/main/java/com/ccorrads/ossp/core/network/models/RegisterRequest.kt
  android/home/.gitignore
  android/home/build.gradle
  android/home/coverage.gradle
  android/home/proguard-rules.pro
  android/home/src/androidTest/java/com/ccorrads/ossp/home/ExampleInstrumentedTest.java
  android/home/src/main/AndroidManifest.xml
  android/home/src/main/java/com/ccorrads/ossp/home/HomeActivity.kt
  android/home/src/main/java/com/ccorrads/ossp/home/HomeComponent.kt
  android/home/src/main/java/com/ccorrads/ossp/home/HomeFragment.kt
  android/home/src/main/java/com/ccorrads/ossp/home/settings/SettingsFragment.kt
  android/home/src/main/java/com/ccorrads/ossp/home/settings/SettingsModule.kt
  android/home/src/main/java/com/ccorrads/ossp/home/settings/SettingsMvp.kt
  android/home/src/main/java/com/ccorrads/ossp/home/settings/SettingsPresenter.kt
  android/home/src/main/res/drawable/ic_home.xml
  android/home/src/main/res/drawable/ic_settings.xml
  android/home/src/main/res/layout/activity_home.xml
  android/home/src/main/res/layout/fragment_home.xml
  android/home/src/main/res/layout/fragment_settings.xml
  android/home/src/main/res/menu/bottom_nav.xml
  android/home/src/main/res/values/strings.xml
  android/home/src/test/java/com/ccorrads/ossp/home/HomeTests.kt
  android/loginregistration/build.gradle
  android/loginregistration/coverage.gradle
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/AuthMvp.kt
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/LoginRegisterFragment.kt
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/injection/LoginRegisterPresenter.kt
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/registration/RegisterMvp.kt
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/registration/RegistrationFragment.kt
  android/loginregistration/src/main/java/com/ccorrads/ossp/loginregistration/registration/injection/RegisterPresenter.kt
  android/settings.gradle
  gateway-test/routes/currentSession/currentSession.js
  gateway-test/routes/currentSession/index.js
  gateway-test/routes/index.js
  gateway-test/routes/users/createUser.js
Labels: Frontend

#66 Fixed some in dockerfile
  microservices/.dockerignore
  microservices/Dockerfile
Labels: Microservices, bug

#64 Order management
  database/src/main/kotlin/com/ossp/database/controller/UserController.kt
  database/src/main/kotlin/com/ossp/database/model/UserSession.kt
  gateway-test/app.js
  gateway-test/package-lock.json
  gateway-test/package.json
  gateway-test/routes/users/createUser.js
  gateway-test/routes/users/loginUser.js
  microservices/.dockerignore
  microservices/Dockerfile
  microservices/app/__init__.py
  microservices/app/auth/controllers.py
  microservices/app/auth/models.py
  microservices/app/orders/__init__.py
  microservices/app/orders/apis.py
  microservices/app/orders/controllers.py
  microservices/app/orders/models.py
  microservices/config.py
Labels: Microservices
